import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Exo_2 } from 'next/font/google'
import { Roboto } from 'next/font/google'




const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'], // use what you need
  variable: '--font-roboto',
})
const exo2 = Exo_2({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // adjust based on what you need
  variable: '--font-exo2',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Trust Property Keys",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${exo2.variable} antialiased font-exo2 antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
